<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="17576" started-at="2021-02-14T23:21:42 PST" finished-at="2021-02-14T23:21:59 PST">
    <groups>
    </groups>
    <test name="Test" duration-ms="17576" started-at="2021-02-14T23:21:42 PST" finished-at="2021-02-14T23:21:59 PST">
      <class name="homePageTestCases.HomePageHeaderTestCase">
        <test-method status="PASS" signature="setupMethod()[pri:0, instance:homePageTestCases.HomePageHeaderTestCase@33f88ab]" name="setupMethod" is-config="true" duration-ms="2876" started-at="2021-02-14T23:21:56 PST" finished-at="2021-02-14T23:21:59 PST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="PASS" signature="verifyHeader()[pri:0, instance:homePageTestCases.HomePageHeaderTestCase@33f88ab]" name="verifyHeader" duration-ms="495" started-at="2021-02-14T23:21:59 PST" finished-at="2021-02-14T23:21:59 PST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHeader -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:homePageTestCases.HomePageHeaderTestCase@33f88ab]" name="tearDown" is-config="true" duration-ms="160" started-at="2021-02-14T23:21:59 PST" finished-at="2021-02-14T23:21:59 PST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- homePageTestCases.HomePageHeaderTestCase -->
      <class name="homePageTestCases.VerifySignInErrorMessage">
        <test-method status="PASS" signature="setupMethod()[pri:0, instance:homePageTestCases.VerifySignInErrorMessage@2833cc44]" name="setupMethod" is-config="true" duration-ms="4817" started-at="2021-02-14T23:21:42 PST" finished-at="2021-02-14T23:21:47 PST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="PASS" signature="signinError()[pri:0, instance:homePageTestCases.VerifySignInErrorMessage@2833cc44]" name="signinError" duration-ms="2481" started-at="2021-02-14T23:21:47 PST" finished-at="2021-02-14T23:21:50 PST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signinError -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:homePageTestCases.VerifySignInErrorMessage@2833cc44]" name="tearDown" is-config="true" duration-ms="209" started-at="2021-02-14T23:21:50 PST" finished-at="2021-02-14T23:21:50 PST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setupMethod()[pri:0, instance:homePageTestCases.VerifySignInErrorMessage@2833cc44]" name="setupMethod" is-config="true" duration-ms="3239" started-at="2021-02-14T23:21:50 PST" finished-at="2021-02-14T23:21:53 PST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="FAIL" signature="signinError1()[pri:0, instance:homePageTestCases.VerifySignInErrorMessage@2833cc44]" name="signinError1" duration-ms="2136" started-at="2021-02-14T23:21:53 PST" finished-at="2021-02-14T23:21:55 PST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[error message is not expected expected [There ] but found [There was a problem]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: error message is not expected expected [There ] but found [There was a problem]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at homePageTestCases.VerifySignInErrorMessage.signinError1(VerifySignInErrorMessage.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signinError1 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:homePageTestCases.VerifySignInErrorMessage@2833cc44]" name="tearDown" is-config="true" duration-ms="204" started-at="2021-02-14T23:21:56 PST" finished-at="2021-02-14T23:21:56 PST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- homePageTestCases.VerifySignInErrorMessage -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
